language: python
dist: trusty
sudo: required
branches:
  only:
    - develop
    - master
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true

install:
  # Install TA-Lib
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xzvf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..

  # Install Test Deps
  - pip install -U pip
  - pip install "numpy>=1.15.4"
  - pip install TA-Lib
  - pip install coveralls
  - pip install -U setuptools
  - pip install ipython==5.3.0
  - pip install --prefer-binary .
script:
  - ls -al $HOME/.rqalpha/
  - ls -al $HOME/.rqalpha/bundle/
  - rqalpha download-bundle
  - coverage run --source=rqalpha test.py
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.rqalpha/bundle
after_success:
  coveralls
